### ISSUE TITLE
search

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#603]
At the moment, search is not implemented, but it has to be. There should be a search box at the top bar, which should search by keyword either in the inbox or in the current bout. Let's use DynamoDB for search index.

**Comment by dmzaytsev** [comment]
@karato it's a valid bug

**Comment by dmzaytsev** [comment]
@karato  set milestone to 3.0

**Comment by karato** [comment]
> @karato it's a valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment]
@yegor256 I set milestone here to `3.1`, let me know if it is wrong

**Comment by karato** [comment]
> @karato  set milestone to 3.0

@dmzaytsev sure, milestone set to 3.0

**Comment by karato** [comment]
@ikhvostenkov do this task

**Comment by karato** [comment]
@yegor256 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `000-332d7e53`

**Comment by dmzaytsev** [comment]
@ikhvostenkov any updates here?

**Comment by ikhvostenkov** [comment]
@dmzaytsev I've faced with problems with DynamoDB, did not work before with it, but now problem resolved, but I've asked for some break. Could you, please, assign someone else or postpone this task until 8th of Juni, I will be out until this for personal reasons?

**Comment by dmzaytsev** [comment]
@ikhvostenkov no problem

@karato please assign this task to @komaz

**Comment by yegor256** [comment]
@karato assign @komaz to this pls

**Comment by karato** [comment]
> @karato assign @komaz to this pls

@yegor256 of course! @komaz it's your ticket now, please go ahead

**Comment by dmzaytsev** [comment]
@komaz any progress here?

**Comment by dmzaytsev** [comment]
@komaz ping

**Comment by komaz** [comment]
@dmzaytsev no progress here

**Comment by dmzaytsev** [comment]
@komaz if you have any technical questions don't hesitate ask right here in the ticket
also keep in mind 
http://www.teamed.io/policy.html#10
http://www.teamed.io/policy.html#16

**Comment by komaz** [comment]
@dmzaytsev I'm thinking about this issue in background all this time, but it seems to me that even properly identify all `@todo` places can take a while. Now I think a good starting point might be the following:
- method `search(String term)` in `com.netbout.spi.Messages`
- method `messages()` in `com.netbout.spi.Inbox`
- naive iterate-all implementation + tests
- todos to continue
What do you think?

**Comment by dmzaytsev** [comment]
@komaz I agree, please proceed

**Comment by komaz** [comment]
@karato more time please

**Comment by yegor256** [comment]
@komaz I didn't get what `Inbox#messages()` is for... I think we need this:

 * `Pageable<Message> Messages#search(String term)`
 * `Pageable<Bout> Inbox#search(String term)`

That's it.

**Comment by yegor256** [comment]
@komaz or maybe even create a new interface `Searchable<T>` and make sure:

 * `Inbox extends Searchable<Bout>`
 * `Messages extends Searchable<Message>`

**Comment by komaz** [comment]
@yegor256 I don't mind implementing to that way, but my thought was that
user would like to see exact messages in search results over inbox, not
just bouts (otherwise either search in bout functionality is redundant, or
user will have to repeat a search in bouts). Or do you mean the application
code should compose these searches (e.g. find bouts first, then find in
bouts) in order to provide full search result?

**Comment by yegor256** [comment]
@komaz well, I thought that a user will have to find a bout first and than search inside that bout again, to find a message. Just like it happens in Gmail. First, you find an email thread and then you can go through it and find the message you're looking for... what do you think?

**Comment by komaz** [comment]
@yegor256 I played with gmail search and I believe your approach will work fine if bout links in search result will be "search in bout" links – that way user won't need need to repeat the search in opened bouts. Sorry for misunderstanding if that's what you meant in the beginning :)

**Comment by yegor256** [comment]
@komaz yes, that's also possible, but we can do it later. For now it will be good enough to let users search in inbox and find bouts and then search in bouts and find messages. These are two different types of searches.

**Comment by karato** [comment]
> @karato more time please

@komaz yes, take your time, thanks for letting me know

**Comment by komaz** [comment]
@yegor256 fixed in pull request #691

**Comment by karato** [comment]
@yegor256 these 4 puzzles were created in this ticket: `603-0cf011c2`/#700, `603-5d374ee5`, `603-303ccd32`, `603-275d519b`

**Comment by yegor256** [comment]
@komaz check this article: http://www.yegor256.com/2015/02/12/top-down-design.html What you've done here is created some code for yourself, not for me, as your user. I still don't have any search functionality but you are asking me to close the ticket and pay. It's "unfair" :) The search box should have been done first and all the rest should have been marked as "todo"

**Comment by dmzaytsev** [comment]
@yegor256 I'm sure @komaz taken it to account.
Another developers will add the search box in #704 , #702.
These tickets marked as urgent and will be resolved soon, I hope.

@komaz did good job and it would be fair if his job will be paid.
Let's shut our eyes to this ticket. Please keep in mind it's the campus project.
Thanks

**Comment by yegor256** [comment]
@dmzaytsev OK

**Comment by karato** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@karato Quality is good here.

**Comment by karato** [comment]
> @karato Quality is good here.

@elenavolokhova thanks, got it, great to see high-quality tickets here

**Comment by karato** [comment]
@komaz just added 10 mins to @elenavolokhova (for QA), payment ID is `59565025`; Much obliged! I have added **30 mins** to your account in payment "AP-7PB298327B919201C", 502 hours and 31 mins spent; +30 added to your rating, at the moment it is: [+398](http://www.netbout.com/b/35322?open=rating)

**Comment by karato** [comment]
@yegor256 Last 2 puzzles came from here were resolved: `603-0cf011c2`/#700, `603-5d374ee5`/#705

**Comment by 0pdd** [comment]
@yegor256 all 5 puzzles are solved here: [#704](https://github.com/yegor256/netbout/issues/704), [#unknown](), [#unknown](), [#unknown](), [#unknown]().
