### ISSUE TITLE
Bout reply person looks incorrect 

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#835]
I've seen several times the case when the message should be from Alice, but it appears to be from another guy.
For example, see this screenshot
![screenshot from 2015-11-13 17 16 56](https://cloud.githubusercontent.com/assets/1388994/11149428/3e588d44-8a2b-11e5-94fb-8d92286eb2f5.png)

IMHO, the message below (http://www.netbout.com/b/36043#msg512998) looks correct. The author is talking to Alice.
But the upper message (http://www.netbout.com/b/36043#msg512999) is weird. The author is talking to himself (using Alise's words!). It looks like the message is published with wrong user name and icon

One more example:
![screenshot from 2015-11-13 17 17 26](https://cloud.githubusercontent.com/assets/1388994/11149429/42286106-8a2b-11e5-9104-8a6206779c9c.png)
http://www.netbout.com/b/36041#msg512992  looks correct
http://www.netbout.com/b/36041#msg512993  looks wrong

**Comment by dmzaytsev** [comment]
@longtimeago I guess this case out of the scope of the project. 
@yegor256 Is it agent's issue ? what do you think?

**Comment by longtimeago** [comment]
@yegor256 ping :)

**Comment by yegor256** [comment]
@longtimeago yeah, it's not a bug of Netbout. it's just "by design". here it is: https://github.com/teamed/at.teamed.io/blob/master/js/join.js#L31-L38

**Comment by longtimeago** [comment]
@yegor256 should I post the bug on at.teamed.io issue tracker?

**Comment by yegor256** [comment]
@longtimeago I fixed it already

**Comment by longtimeago** [comment]
@yegor256 I'll wait for the next interview assignment to check it if you don't mind :)

**Comment by longtimeago** [comment]
@yegor256 by the way, it still reproduce here http://www.netbout.com/b/36145

**Comment by dmzaytsev** [comment]
@longtimeago could you close this ticket?
actually it out of the scope of the project

**Comment by longtimeago** [comment]
@dmzaytsev OK
